name: Deploy images
on:
  push:
    branches:
      - main

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'login to github'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'build and push'
        run: |
            docker build . --tag ghcr.io/${{ github.repository_owner }}/hello:latest
            docker push ghcr.io/${{ github.repository_owner }}/hello:latest
      
