name: Manual Workflows
on: 
 workflow_dispatch:
jobs:
 run-manual-tasks:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Info
        run:
         echo "Running manual tasks"
