name: Push Events
on: 
 schedule:
   - cron: '*/2 * * * *' #every 5 minute
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: Info
        run:
         echo "this is push event"
